# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsq < Formula
  desc "A simple DNS Lookup utility"
  homepage "https://github.com/sunggun-yu/dnsq"
  version "1.4.0"

  on_macos do
    url "https://github.com/sunggun-yu/dnsq/releases/download/v1.4.0/dnsq_darwin_all.tar.gz"
    sha256 "5831b14649e903303c0fb506b50796648671881065b889e25745f4f062446c4e"

    def install
      bin.install "dnsq"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sunggun-yu/dnsq/releases/download/v1.4.0/dnsq_linux_amd64.tar.gz"
        sha256 "b72e96a30b3059a2271d08910d161a2efb9d4e7892bde8c3f39f419b7a371dc2"

        def install
          bin.install "dnsq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sunggun-yu/dnsq/releases/download/v1.4.0/dnsq_linux_arm64.tar.gz"
        sha256 "a7c6ef88c390c640f413e3932c4624c4c83d541872c5c1fea88b24394c882f92"

        def install
          bin.install "dnsq"
        end
      end
    end
  end
end
