# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsq < Formula
  desc "A simple DNS Lookup utility"
  homepage "https://github.com/sunggun-yu/dnsq"
  version "1.2.2"

  on_macos do
    url "https://github.com/sunggun-yu/dnsq/releases/download/v1.2.2/dnsq_darwin_all.tar.gz"
    sha256 "389938403fefd718e1fea13d0907ee3fed07b198f9edb95bf52c55253649dc9c"

    def install
      bin.install "dnsq"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sunggun-yu/dnsq/releases/download/v1.2.2/dnsq_linux_amd64.tar.gz"
        sha256 "fc60dd9d7f66a7e903483bcbc589353cd5f538b1b9e0349d34b993b9cac5bdc3"

        def install
          bin.install "dnsq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sunggun-yu/dnsq/releases/download/v1.2.2/dnsq_linux_arm64.tar.gz"
        sha256 "d2c2d04aa4eb47aa2b3f1f17288634a9db1f22fca3242f0cbf335986baf1a286"

        def install
          bin.install "dnsq"
        end
      end
    end
  end
end
