# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsq < Formula
  desc "A simple DNS Lookup utility"
  homepage "https://github.com/sunggun-yu/dnsq"
  version "1.1.1"

  on_macos do
    url "https://github.com/sunggun-yu/dnsq/releases/download/v1.1.1/dnsq_darwin_all.tar.gz"
    sha256 "730a27660a18dad95151c9edb5f2177e405968e229721b84e566a30dae17892a"

    def install
      bin.install "dnsq"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sunggun-yu/dnsq/releases/download/v1.1.1/dnsq_linux_amd64.tar.gz"
        sha256 "b4ffa5c84b9469352dd44b39371d8a2125e29563b6f7e6d01bc04186509e1b4f"

        def install
          bin.install "dnsq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sunggun-yu/dnsq/releases/download/v1.1.1/dnsq_linux_arm64.tar.gz"
        sha256 "b33cb9faf898cb0b95ce2bacf18f5e3ca56d622a4123bc66cd8745b4dd72df8b"

        def install
          bin.install "dnsq"
        end
      end
    end
  end
end
