# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envp < Formula
  desc "Cli wrapper to set profile based environment variables for your command line execution"
  homepage "https://github.com/sunggun-yu/envp"
  version "0.0.1-alpha.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/envp/releases/download/v0.0.1-alpha.2/envp_0.0.1-alpha.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6e57b91eb7fc47a4ad83d56f6576d58bc2add2693bb9f8e7fc395375c954a411"

      def install
        bin.install "envp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunggun-yu/envp/releases/download/v0.0.1-alpha.2/envp_0.0.1-alpha.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e0b074f700f0190f4e2c4a65595bcade835da5bcd902e63964416f2393c2a22a"

      def install
        bin.install "envp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/envp/releases/download/v0.0.1-alpha.2/envp_0.0.1-alpha.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "546b9e2d0b64dc73d62e3970ee4a268b33fe098787b6615e458959b689961b66"

      def install
        bin.install "envp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunggun-yu/envp/releases/download/v0.0.1-alpha.2/envp_0.0.1-alpha.2_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "62168fc417c28fc5e35289a15aa97b18d93eabc607a102f427587dfc79e25dd6"

      def install
        bin.install "envp"
      end
    end
  end

  test do
    system "#{bin}/envp -v"
  end
end
