# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhAppAccessToken < Formula
  desc "Cli wrapper to set profile based environment variables for your command line execution"
  homepage "https://github.com/sunggun-yu/gh-app-access-token-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/gh-app-access-token-cli/releases/download/v0.0.1/gh-app-access-token_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f5f19d12ea88965a30d9ca776ed3362b6bcacb1703f1996e855f0dcd24d65d4d"

      def install
        bin.install "gh-app-access-token"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunggun-yu/gh-app-access-token-cli/releases/download/v0.0.1/gh-app-access-token_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1ff416a064d78bfb0fdd2a3172b0250ab1979a81b370ede14441c9843a0c2888"

      def install
        bin.install "gh-app-access-token"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunggun-yu/gh-app-access-token-cli/releases/download/v0.0.1/gh-app-access-token_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "92c6653a1e01e3cebd310d631e60a4f5fccb362053eacac8ebb3f87f61118c18"

      def install
        bin.install "gh-app-access-token"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/gh-app-access-token-cli/releases/download/v0.0.1/gh-app-access-token_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "02f88c2703d559c59902f3a8b5618237dc52f7ff2a1afcd222d0bfebadc1cec4"

      def install
        bin.install "gh-app-access-token"
      end
    end
  end

  test do
    system "#{bin}/gh-app-access-token -v"
  end
end
