# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwksToPem < Formula
  desc "A simple cli tool to convert jwks to pem"
  homepage "https://github.com/sunggun-yu/jwks-to-pem-cli"
  version "0.0.1"

  on_macos do
    url "https://github.com/sunggun-yu/jwks-to-pem-cli/releases/download/v0.0.1/jwks-to-pem_darwin_all.tar.gz"
    sha256 "67764d55f81570d7bbb06cb1792182d397bd4d497e408df64484c6ae5a8996c4"

    def install
      bin.install "jwks-to-pem"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunggun-yu/jwks-to-pem-cli/releases/download/v0.0.1/jwks-to-pem_linux_arm64.tar.gz"
      sha256 "813e09e25c29f12889a02206d82bb5e93459aad8067c5a8cf525d53844e06784"

      def install
        bin.install "jwks-to-pem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/jwks-to-pem-cli/releases/download/v0.0.1/jwks-to-pem_linux_amd64.tar.gz"
      sha256 "07c1d55b9d2b812aa57ef8ef1efce3cca147a2cc9a635f03779dc6fde31d4c77"

      def install
        bin.install "jwks-to-pem"
      end
    end
  end
end
