# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwksToPem < Formula
  desc "A simple cli tool to convert jwks to pem"
  homepage "https://github.com/sunggun-yu/jwks-to-pem-cli"
  version "0.0.3"

  on_macos do
    url "https://github.com/sunggun-yu/jwks-to-pem-cli/releases/download/v0.0.3/jwks-to-pem_darwin_all.tar.gz"
    sha256 "02abb0b723ac062728fe6aec40363604b36df75a1d87809afcd1f8796eb8130c"

    define_method(:install) do
      bin.install "jwks-to-pem"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunggun-yu/jwks-to-pem-cli/releases/download/v0.0.3/jwks-to-pem_linux_amd64.tar.gz"
      sha256 "0d8a402b9dcab4ee98138ca9f37eb0ff424f9652aadef1baa709ec7dddd95f1d"
      define_method(:install) do
        bin.install "jwks-to-pem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunggun-yu/jwks-to-pem-cli/releases/download/v0.0.3/jwks-to-pem_linux_arm64.tar.gz"
      sha256 "baf125b5607a9f0606c2dd7b5a041790620d8b7293dec7301df8b6dbad1e9c15"
      define_method(:install) do
        bin.install "jwks-to-pem"
      end
    end
  end
end
