# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twofa < Formula
  desc "Two-factor authentication on the command line"
  homepage "https://github.com/sunggun-yu/2fa"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/2fa/releases/download/v1.2.1/2fa_1.2.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "71edbbd947d82c840ebe8f80b1193b94abd78ea2b95c6d5f63416e7690471e20"

      def install
        bin.install "2fa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunggun-yu/2fa/releases/download/v1.2.1/2fa_1.2.1_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2e3c97d82119f4ff0c8d4b35cd0a5cb3a9fc15e96365c40cdf7e7d6dff6ee921"

      def install
        bin.install "2fa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunggun-yu/2fa/releases/download/v1.2.1/2fa_1.2.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "3bbd0fe33a67850768a66831e3370e6a2e17d70ff1600b18dba32568dc540ee4"

      def install
        bin.install "2fa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sunggun-yu/2fa/releases/download/v1.2.1/2fa_1.2.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d2547589b7fe3035be2a939d3525c311c3882da956db70a50087c819fa71a24e"

      def install
        bin.install "2fa"
      end
    end
  end

  test do
    system "#{bin}/2fa -v"
  end
end
